services:
  matcha:
    image: portofolio
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: portofolio
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules